version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  redis:
    image: redis
    container_name: redis
    ports:
      - "63792:6379"
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: system-rezerwacji
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      REDIS_HOST: redis
#      POSTGRES_HOST: postgres
#    restart: always


volumes:
  postgres_data: