services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"

  eureka:
    image: 140023391826.dkr.ecr.eu-central-1.amazonaws.com/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always

  api-gateway:
    image: 140023391826.dkr.ecr.eu-central-1.amazonaws.com/api-gateway
    container_name: api-gateway
    ports:
      - "8060:8060"
    depends_on:
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    restart: always

  payment-validation-service:
    image: 140023391826.dkr.ecr.eu-central-1.amazonaws.com/payment-validation-service
    container_name: payment-validation-service
    depends_on:
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    restart: always

  code-delivery-service:
    image: 140023391826.dkr.ecr.eu-central-1.amazonaws.com/code-delivery-service
    container_name: code-delivery-service
    depends_on:
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    restart: always



  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system-rezerwacji
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    restart: always

  reservation-front:
    container_name: reservation-front
    image: 140023391826.dkr.ecr.eu-central-1.amazonaws.com/front-reservation
    restart: always
    ports:
      - "80:80"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always



volumes:
  postgres_data: