#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/reservations
#    username: root
#    password: hard
#  jpa:
#    hibernate:
#      ddl-auto: update
#  sql:
#    init:
#      mode: always
spring:
  application:
    name: SystemRezerwacji_TDD
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
