spring:
#  application:
#    name: SystemRezerwacji_TDD
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: validate
#  h2:
#    console:
#      enabled: true
