spring:
  flyway:
    enabled: false
  application:
    name: SystemRezerwacji_TDD
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always


  cache:
    type: redis
    redis:
      time-to-live: PT30M

  mail:
    host: smtp.gmail.com
    port: 587
    username: rezerwacje.bialystok3@gmail.com
    password: arqd kyql ouvh qqtk
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
        starttls:
          enable: true
          required: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:63792}


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

reservation:
  send-remind: "0 0 9 * * *"


auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET:ababababbbsadfweawgehrth}
    issuer: sb-reservation-system-backend





