spring:
  flyway:
    enabled: false
  application:
    name: SystemRezerwacji_TDD
  datasource:
    url: jdbc:postgresql://postgres:5432/reservations #jesli chce uruchomic bez dockera to zmien na localhost zamiast postgress
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always


  cache:
    type: redis
    redis:
      time-to-live: PT30M

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:63792}


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

reservation:
  send-remind: "0 0 9 * * *"

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET:ababababbbsadfweawgehrth}
    issuer: sb-reservation-system-backend

mail:
  sender:
    http:
      client:
        config:
          connectionTimeout: 1000
          port: 8080
          readTimeout: 1000
          uri: http://ec2-52-28-34-183.eu-central-1.compute.amazonaws.com



