#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/reservations
#    username: root
#    password: hard
#  jpa:
#    hibernate:
#      ddl-auto: update
#  sql:
#    init:
#      mode: always
spring:
  application:
    name: SystemRezerwacji_TDD
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rezerwacje.bialystok3@gmail.com
    password: arqd kyql ouvh qqtk
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

